### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by samfloKIT** [jflepp/PicoMailForms#3]
Hello,

I tried to use PicoMailForms but I've got HTTP ERROR 500 after installed your plugin on every Pico page ;-)
The Apache Error Log shows:
`[Thu Apr 18 13:06:34.151545 2019] [:error] [pid 32417] [client 82.X.X.X:yyyyy] PHP Fatal error:  Declaration of PicoMailFormsPlugin::__construct($pico) must be compatible with PicoPluginInterface::__construct(Pico $pico) in /<PICO_ROOT>/plugins/PicoMailFormsPlugin/PicoMailFormsPlugin.php on line 3`

My System:
Ubuntu 16.04.6 LTS
Apache/2.4.18 (Ubuntu)
PHP 7.0.33-0ubuntu0.16.04.3 (cli)
Pico 2.0.4

I've installed PicoCMS and PicoMailForm with composer (after installing composer):
`$ curl -sSL https://getcomposer.org/installer | php`
`$ sudo -su www-data`
`$ cd /var/www/html/`
`$ php ~/composer.phar create-project picocms/pico-composer pico`
`$ cd pico`
`$ php ~/composer.phar require jflepp/picomailformsplugin`

Did I make any mistakes during the installation or is there any issue in PicoMailForm?

Kind regards.

**Comment by fl3pp** [comment]
Hi @samfloKIT,

Thank you for submitting this issue. 

Could you try to update your PHP to version 7.2.X? Unfortunately I am not able to reproduce your error and I am not planning to support out of date PHP versions.
PHP 7.0 stopped support by 2019. See [PHP Supported Version](https://www.php.net/supported-versions.php).

Let me know if your problem has been solved using a newer PHP Version.

Best regards

**Comment by fl3pp** [comment]
Closed due to inactivity

**Comment by evansmith110610** [comment]
I have the same error message. Unfortunately my server cannot be upgraded past PHP 7.0 at the moment.

**Comment by evansmith110610** [comment]
Looks like that web hosting company hasn't updated past PHP 7.0 and will inform me when they do. I migrated the site to a server with PHP 7.2 and there is no fatal error.

**Comment by fl3pp** [comment]
Hello @evansmith110610,

Thank you for your response. 
I'm glad that your problem could be solved by using a supported PHP version.

Please understand that I just built the project because I missed this functionality in Pico for a website of myself. As the website is now life, I'm going to fix urgent issues and help if possible but cannot garantee that the library will work on out-of-date platforms.

If you want to, you can investigate further by yourself by using the `debug/SetupTestSite.ps1` script and a debugger. I would gladly accept merge requests fixing problems.

I wish you the best of luck for your project.

Best regards
